### ISSUE TITLE
datamodel-loader.yaml  is not working for connecting active chassis 

### ISSUE THREAD

**Issue by ShreePatilMA** [Spirent/stc-ansible#35]
Hi , We are trying to use datamodel-loader.yaml  . Saved  working  windows GUI traffic pattern into xml file.  Downloaded xml file into asset directory as datamodel.xml  The ansible playbook runs but the chassis is offline state.

debian@stc-deb-0:~/stc-ansible$ ./emulator.py -labserver 192.168.49.180 datamodel-loader.yaml 
Testing playbook datamodel-loader.yaml with lab server 192.168.49.180 and chassis []
------------ TASK Create session ------------
Traceback (most recent call last):
  File "./emulator.py", line 43, in <module>
    emulator.play(args.playbook)
  File "/home/debian/stc-ansible/tests/playbook.py", line 94, in play
    result = model.action(task["stc"])
  File "/home/debian/stc-ansible/module_utils/metamodel.py", line 92, in action
    result = self.new_session(params["user"], params["name"], chassis, propsDict, reset_existing, kill_existing)
  File "/home/debian/stc-ansible/module_utils/metamodel.py", line 239, in new_session    
    if not self.rest.new_session(user_name, session_name, reset_existing, kill_existing):  File "/home/debian/stc-ansible/module_utils/stcrest.py", line 38, in new_session       
    systemInfo = json.loads(conn.get(url).content)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

**Comment by ShreePatilMA** [comment]
[Data-model-log-vls-server.docx](https://github.com/Spirent/stc-ansible/files/10483733/Data-model-log-vls-server.docx)
Attached vls server log

**Comment by ShreePatilMA** [comment]
Resolved adding port reservation setps
